version: '3'
services:
  database:
    build:
      context: ./Database/
    ports:
      - "27017:27017"
  api:
    build:
      context: ./Api/
    ports:
      - "8000:5001"
    depends_on:
      - database

